
CREATE TABLE public."USR_USUARIOS" (
	"USR_CODIGO" serial4 NOT NULL,
	"USR_NUMERO_DOCUMENTO" varchar(15) NOT NULL,
	"USR_NOMBRE" varchar(100) NOT NULL,
	"USR_CORREO" varchar(100) NOT NULL,
	"USR_CLAVE_ACCESO" varchar(1000) NOT NULL,
	"USR_ROL_ACCESO" varchar(20) NULL,
	CONSTRAINT "USR_USUARIOS_pkey" PRIMARY KEY ("USR_CODIGO"),
	CONSTRAINT seguridad_usr_usuarios_usr_correo_unique UNIQUE ("USR_CORREO"),
	CONSTRAINT seguridad_usr_usuarios_usr_numero_documento_unique UNIQUE ("USR_NUMERO_DOCUMENTO")
);

CREATE TABLE public."EMP_EMPLEADOS" (
	"EMP_CODIGO" serial4 NOT NULL,
	"EMP_NOMBRE" varchar(100) NOT NULL,
	"EMP_FECHA_INGRESO" date NOT NULL,
	"EMP_SALARIO" numeric(15, 2) NOT NULL,
	CONSTRAINT "EMP_EMPLEOS_pkey" PRIMARY KEY ("EMP_CODIGO")
);


CREATE TABLE public."SLC_SOLICITUDES" (
	"SLC_CODIGO" serial4 NOT NULL,
	"SLC_CODIGO_REFERENCIA" varchar(50) NOT NULL,
	"SLC_DESCRIPCION" varchar(50) NOT NULL,
	"SLC_RESUMEN" varchar(50) NOT NULL,
	"SLC_CODEMP_EMPLEADO" int4 NOT NULL,
	CONSTRAINT "SLC_SOLICITUDES_pkey" PRIMARY KEY ("SLC_CODIGO")
);


-- public."SLC_SOLICITUDES" foreign keys

ALTER TABLE public."SLC_SOLICITUDES" ADD CONSTRAINT "FK_SLC_EMP" FOREIGN KEY ("SLC_CODEMP_EMPLEADO") REFERENCES public."EMP_EMPLEADOS"("EMP_CODIGO") ON DELETE CASCADE;